modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory
modId="dtbop" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Dynamic Trees for Biomes o' Plenty" #mandatory
updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/BOP.json?raw=true" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/dtbop" #optional
logoFile="" #optional
credits="ferreusveritas" #optional
authors="mangoose, Max Hyper" #optional

description='''
Compatibility Mod between Dynamic trees and Biomes o' plenty
'''

[[dependencies.dtbop]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.dtbop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtbop]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.3.0-BETA2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtbop]]
    modId="dynamictreesplus"
    mandatory=false
    versionRange="[1.3.0-BETA1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtbop]]
    modId="biomesoplenty"
    mandatory=true
    versionRange="[18.0.0.0,)"
    ordering="AFTER"
    side="BOTH"
